#ifndef ATOMS_H
#define ATOMS_H

#include <xcb/xproto.h>

// TODO: if we have multiple connections (for example, multi-screen without Xinerama),
// translations might differ between connections.

// <X11/Xatom.h> defines XA_LAST_PREDEFINED, but <xcb/xproto.h> doesn't for xcb_atom_enum_t.
#define AAWM_LAST_X11_PREDEFINED_ATOM 68
#define AAWM_LAST_MAPPED_ATOM 73

// Makes more sense for get_atom_from_symbol to use an enum like xcb.
#define AAWM_ATOM_UTF8_STRING (AAWM_LAST_X11_PREDEFINED_ATOM + 1) // 238

#define AAWM_ATOM_WM_PROTOCOLS (AAWM_LAST_X11_PREDEFINED_ATOM + 2) // 242
#define AAWM_ATOM_WM_TAKE_FOCUS (AAWM_LAST_X11_PREDEFINED_ATOM + 3) // 243
#define AAWM_ATOM_WM_SAVE_YOURSELF (AAWM_LAST_X11_PREDEFINED_ATOM + 4)
#define AAWM_ATOM_WM_DELETE_WINDOW (AAWM_LAST_X11_PREDEFINED_ATOM + 5) // 240

// Following ones aren't properly defined yet.

#define AAWM_ATOM_WM_CLIENT_LEADER (AAWM_LAST_X11_PREDEFINED_ATOM + 6) // 239
#define AAWM_ATOM_WM_LOCALE_NAME (AAWM_LAST_X11_PREDEFINED_ATOM + 7) // 241
#define AAWM_ATOM_WM_WINDOW_ROLE (AAWM_LAST_X11_PREDEFINED_ATOM +8) // 244

#define AAWM_ATOM_NET_WM_DESKTOP (AAWM_LAST_X11_PREDEFINED_ATOM + 9) // 250
#define AAWM_ATOM_NET_WM_ICON (AAWM_LAST_X11_PREDEFINED_ATOM + 10) // 251
#define AAWM_ATOM_NET_WM_ICON_NAME (AAWM_LAST_X11_PREDEFINED_ATOM + 11) // 252
#define AAWM_ATOM_NET_WM_NAME (AAWM_LAST_X11_PREDEFINED_ATOM + 12) // 253
#define AAWM_ATOM_NET_WM_PID (AAWM_LAST_X11_PREDEFINED_ATOM + 13) //254
#define AAWM_ATOM_NET_WM_PING (AAWM_LAST_X11_PREDEFINED_ATOM + 14) // 255

#define AAWM_ATOM_NET_WM_STATE (AAWM_LAST_X11_PREDEFINED_ATOM + 15) // 256
#define AAWM_ATOM_NET_WM_STATE_ABOVE (AAWM_LAST_X11_PREDEFINED_ATOM + 16) // 257
#define AAWM_ATOM_NET_WM_STATE_BELOW (AAWM_LAST_X11_PREDEFINED_ATOM + 17) // 258
#define AAWM_ATOM_NET_WM_STATE_HIDDEN (AAWM_LAST_X11_PREDEFINED_ATOM + 18) // 260
#define AAWM_ATOM_NET_WM_STATE_MODAL (AAWM_LAST_X11_PREDEFINED_ATOM + 19) // 261
#define AAWM_ATOM_NET_WM_STATE_MAXIMIZED_VERT (AAWM_LAST_X11_PREDEFINED_ATOM + 20) // 261
#define AAWM_ATOM_NET_WM_STATE_MAXIMIZED_HORZ (AAWM_LAST_X11_PREDEFINED_ATOM + 21) // 262
#define AAWM_ATOM_NET_WM_STATE_STICKY (AAWM_LAST_X11_PREDEFINED_ATOM + 22) // 265
#define AAWM_ATOM_NET_WM_STATE_STAYS_ON_TOP (AAWM_LAST_X11_PREDEFINED_ATOM + 23) // 331

#define AAWM_ATOM_NET_WM_SYNC_REQUEST (AAWM_LAST_X11_PREDEFINED_ATOM + 24) // 266, 267
#define AAWM_ATOM_NET_WM_SYNC_REQUEST_COUNTER (AAWM_LAST_X11_PREDEFINED_ATOM + 25) // 268

#define AAWM_ATOM_NET_WM_WINDOW_TYPE (AAWM_LAST_X11_PREDEFINED_ATOM + 26) // 269
#define AAWM_ATOM_NET_WM_WINDOW_TYPE_DIALOG (AAWM_LAST_X11_PREDEFINED_ATOM + 27) // 271
#define AAWM_ATOM_NET_WM_WINDOW_TYPE_NORMAL (AAWM_LAST_X11_PREDEFINED_ATOM + 28) // 275
#define AAWM_ATOM_NET_WM_WINDOW_TYPE_UTILITY (AAWM_LAST_X11_PREDEFINED_ATOM + 29) // 278
#define AAWM_ATOM_NET_WM_WINDOW_TYPE_DOCK (AAWM_LAST_X11_PREDEFINED_ATOM + 30) // 332
#define AAWM_ATOM_NET_WM_WINDOW_TYPE_SPLASH (AAWM_LAST_X11_PREDEFINED_ATOM + 31) // 399

#define AAWM_ATOM_MANAGER (AAWM_LAST_X11_PREDEFINED_ATOM + 32) // 276 ???
#define AAWM_ATOM_NET_WM_USER_TIME_WINDOW (AAWM_LAST_X11_PREDEFINED_ATOM + 33) // 277
#define AAWM_ATOM_NET_WM_OPAQUE_REGION (AAWM_LAST_X11_PREDEFINED_ATOM + 34) // 297
#define AAWM_ATOM_MOTIF_WM_HINTS (AAWM_LAST_X11_PREDEFINED_ATOM + 35) // 333
#define AAWM_ATOM_NET_WM_STRUT_PARTIAL (AAWM_LAST_X11_PREDEFINED_ATOM + 36) // 334
#define AAWM_ATOM_NET_DESKTOP_LAYOUT_S0 (AAWM_LAST_X11_PREDEFINED_ATOM + 37) // 336

// Check what XdndAware is.

// Defined in "aawm_ctx.h"
struct aawm_ctx;

const char * get_atom_name( struct aawm_ctx * a_ctx, xcb_atom_t a_atom );
const char ** alloc_atom_names_list( struct aawm_ctx * a_ctx, size_t a_len, xcb_atom_t *a_list );
xcb_atom_t get_atom_from_symbol( struct aawm_ctx * a_ctx, int a_symbol );

#endif
