#ifndef ATOMS_H
#define ATOMS_H

#include <xcb/xproto.h>

// TODO: if we have multiple connections (for example, multi-screen without Xinerama),
// translations might differ between connections.

// <X11/Xatom.h> defines XA_LAST_PREDEFINED, but <xcb/xproto.h> doesn't for xcb_atom_enum_t.
#define AAWM_LAST_X11_PREDEFINED_ATOM 68
#define AAWM_LAST_MAPPED_ATOM 143

typedef enum aawm_atom_enum_t { // extends xcb_atom_enum_t.
    AAWM_ATOM_NONE = 0,
    AAWM_ATOM_ANY = 0,
    AAWM_ATOM_PRIMARY = 1,
    AAWM_ATOM_SECONDARY = 2,
    AAWM_ATOM_ARC = 3,
    AAWM_ATOM_ATOM = 4,
    AAWM_ATOM_BITMAP = 5,
    AAWM_ATOM_CARDINAL = 6,
    AAWM_ATOM_COLORMAP = 7,
    AAWM_ATOM_CURSOR = 8,
    AAWM_ATOM_CUT_BUFFER0 = 9,
    AAWM_ATOM_CUT_BUFFER1 = 10,
    AAWM_ATOM_CUT_BUFFER2 = 11,
    AAWM_ATOM_CUT_BUFFER3 = 12,
    AAWM_ATOM_CUT_BUFFER4 = 13,
    AAWM_ATOM_CUT_BUFFER5 = 14,
    AAWM_ATOM_CUT_BUFFER6 = 15,
    AAWM_ATOM_CUT_BUFFER7 = 16,
    AAWM_ATOM_DRAWABLE = 17,
    AAWM_ATOM_FONT = 18,
    AAWM_ATOM_INTEGER = 19,
    AAWM_ATOM_PIXMAP = 20,
    AAWM_ATOM_POINT = 21,
    AAWM_ATOM_RECTANGLE = 22,
    AAWM_ATOM_RESOURCE_MANAGER = 23,
    AAWM_ATOM_RGB_COLOR_MAP = 24,
    AAWM_ATOM_RGB_BEST_MAP = 25,
    AAWM_ATOM_RGB_BLUE_MAP = 26,
    AAWM_ATOM_RGB_DEFAULT_MAP = 27,
    AAWM_ATOM_RGB_GRAY_MAP = 28,
    AAWM_ATOM_RGB_GREEN_MAP = 29,
    AAWM_ATOM_RGB_RED_MAP = 30,
    AAWM_ATOM_STRING = 31,
    AAWM_ATOM_VISUALID = 32,
    AAWM_ATOM_WINDOW = 33,
    AAWM_ATOM_WM_COMMAND = 34,
    AAWM_ATOM_WM_HINTS = 35,
    AAWM_ATOM_WM_CLIENT_MACHINE = 36,
    AAWM_ATOM_WM_ICON_NAME = 37,
    AAWM_ATOM_WM_ICON_SIZE = 38,
    AAWM_ATOM_WM_NAME = 39,
    AAWM_ATOM_WM_NORMAL_HINTS = 40,
    AAWM_ATOM_WM_SIZE_HINTS = 41,
    AAWM_ATOM_WM_ZOOM_HINTS = 42,
    AAWM_ATOM_MIN_SPACE = 43,
    AAWM_ATOM_NORM_SPACE = 44,
    AAWM_ATOM_MAX_SPACE = 45,
    AAWM_ATOM_END_SPACE = 46,
    AAWM_ATOM_SUPERSCRIPT_X = 47,
    AAWM_ATOM_SUPERSCRIPT_Y = 48,
    AAWM_ATOM_SUBSCRIPT_X = 49,
    AAWM_ATOM_SUBSCRIPT_Y = 50,
    AAWM_ATOM_UNDERLINE_POSITION = 51,
    AAWM_ATOM_UNDERLINE_THICKNESS = 52,
    AAWM_ATOM_STRIKEOUT_ASCENT = 53,
    AAWM_ATOM_STRIKEOUT_DESCENT = 54,
    AAWM_ATOM_ITALIC_ANGLE = 55,
    AAWM_ATOM_X_HEIGHT = 56,
    AAWM_ATOM_QUAD_WIDTH = 57,
    AAWM_ATOM_WEIGHT = 58,
    AAWM_ATOM_POINT_SIZE = 59,
    AAWM_ATOM_RESOLUTION = 60,
    AAWM_ATOM_COPYRIGHT = 61,
    AAWM_ATOM_NOTICE = 62,
    AAWM_ATOM_FONT_NAME = 63,
    AAWM_ATOM_FAMILY_NAME = 64,
    AAWM_ATOM_FULL_NAME = 65,
    AAWM_ATOM_CAP_HEIGHT = 66,
    AAWM_ATOM_WM_CLASS = 67,
    AAWM_ATOM_WM_TRANSIENT_FOR = 68,

	// ICCCM
	AAWM_ATOM_WM_PROTOCOLS = (AAWM_LAST_X11_PREDEFINED_ATOM + 1),
	AAWM_ATOM_WM_TAKE_FOCUS = (AAWM_LAST_X11_PREDEFINED_ATOM + 2),
	AAWM_ATOM_WM_SAVE_YOURSELF = (AAWM_LAST_X11_PREDEFINED_ATOM + 3),
	AAWM_ATOM_WM_DELETE_WINDOW = (AAWM_LAST_X11_PREDEFINED_ATOM + 4),

	AAWM_ATOM_WM_CLIENT_LEADER = (AAWM_LAST_X11_PREDEFINED_ATOM + 5),
	AAWM_ATOM_WM_WINDOW_ROLE = (AAWM_LAST_X11_PREDEFINED_ATOM + 6),

	// EWMH
	AAWM_ATOM_UTF8_STRING = (AAWM_LAST_X11_PREDEFINED_ATOM + 7),

	AAWM_ATOM_NET_SUPPORTED = (AAWM_LAST_X11_PREDEFINED_ATOM + 8),
	AAWM_ATOM_NET_CLIENT_LIST = (AAWM_LAST_X11_PREDEFINED_ATOM + 9),
	AAWM_ATOM_NET_CLIENT_LIST_STACKING = (AAWM_LAST_X11_PREDEFINED_ATOM + 10),
	AAWM_ATOM_NET_NUMBER_OF_DESKTOPS = (AAWM_LAST_X11_PREDEFINED_ATOM + 11),
	AAWM_ATOM_NET_DESKTOP_GEOMETRY = (AAWM_LAST_X11_PREDEFINED_ATOM + 12),
	AAWM_ATOM_NET_DESKTOP_VIEWPORT = (AAWM_LAST_X11_PREDEFINED_ATOM + 13),
	AAWM_ATOM_NET_CURRENT_DESKTOP = (AAWM_LAST_X11_PREDEFINED_ATOM + 14),
	AAWM_ATOM_NET_DESKTOP_NAMES = (AAWM_LAST_X11_PREDEFINED_ATOM + 15),
	AAWM_ATOM_NET_ACTIVE_WINDOW = (AAWM_LAST_X11_PREDEFINED_ATOM + 16),
	AAWM_ATOM_NET_WORKAREA = (AAWM_LAST_X11_PREDEFINED_ATOM + 17),
	AAWM_ATOM_NET_SUPPORTING_WM_CHECK = (AAWM_LAST_X11_PREDEFINED_ATOM + 18),
	AAWM_ATOM_NET_VIRTUAL_ROOTS = (AAWM_LAST_X11_PREDEFINED_ATOM + 19),
	AAWM_ATOM_NET_DESKTOP_LAYOUT = (AAWM_LAST_X11_PREDEFINED_ATOM + 20),
	AAWM_ATOM_NET_SHOWING_DESKTOP = (AAWM_LAST_X11_PREDEFINED_ATOM + 21),

	AAWM_ATOM_NET_CLOSE_WINDOW = (AAWM_LAST_X11_PREDEFINED_ATOM + 22),
	AAWM_ATOM_NET_MOVERESIZE_WINDOW = (AAWM_LAST_X11_PREDEFINED_ATOM + 23),
	AAWM_ATOM_NET_WM_MOVERESIZE = (AAWM_LAST_X11_PREDEFINED_ATOM + 24),
	AAWM_ATOM_NET_RESTACK_WINDOW = (AAWM_LAST_X11_PREDEFINED_ATOM + 25),
	AAWM_ATOM_NET_REQUEST_FRAME_EXTENTS = (AAWM_LAST_X11_PREDEFINED_ATOM + 26),

	AAWM_ATOM_NET_WM_NAME = (AAWM_LAST_X11_PREDEFINED_ATOM + 27),
	AAWM_ATOM_NET_WM_VISIBLE_NAME = (AAWM_LAST_X11_PREDEFINED_ATOM + 28),
	AAWM_ATOM_NET_WM_ICON_NAME = (AAWM_LAST_X11_PREDEFINED_ATOM + 29),
	AAWM_ATOM_NET_WM_VISIBLE_ICON_NAME = (AAWM_LAST_X11_PREDEFINED_ATOM + 30),
	AAWM_ATOM_NET_WM_DESKTOP = (AAWM_LAST_X11_PREDEFINED_ATOM + 31),

	AAWM_ATOM_NET_WM_WINDOW_TYPE = (AAWM_LAST_X11_PREDEFINED_ATOM + 32),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_DESKTOP = (AAWM_LAST_X11_PREDEFINED_ATOM + 33),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_DOCK = (AAWM_LAST_X11_PREDEFINED_ATOM + 34),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_TOOLBAR = (AAWM_LAST_X11_PREDEFINED_ATOM + 35),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_MENU = (AAWM_LAST_X11_PREDEFINED_ATOM + 36),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_UTILITY = (AAWM_LAST_X11_PREDEFINED_ATOM + 37),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_SPLASH = (AAWM_LAST_X11_PREDEFINED_ATOM + 38),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_DIALOG = (AAWM_LAST_X11_PREDEFINED_ATOM + 39),
	AAWM_ATOM_NET_WM_WINDOW_TYPE_NORMAL = (AAWM_LAST_X11_PREDEFINED_ATOM + 40),

	AAWM_ATOM_NET_WM_STATE = (AAWM_LAST_X11_PREDEFINED_ATOM + 41),
	AAWM_ATOM_NET_WM_STATE_MODAL = (AAWM_LAST_X11_PREDEFINED_ATOM + 42),
	AAWM_ATOM_NET_WM_STATE_STICKY = (AAWM_LAST_X11_PREDEFINED_ATOM + 43),
	AAWM_ATOM_NET_WM_STATE_MAXIMIZED_VERT = (AAWM_LAST_X11_PREDEFINED_ATOM + 44),
	AAWM_ATOM_NET_WM_STATE_MAXIMIZED_HORZ = (AAWM_LAST_X11_PREDEFINED_ATOM + 45),
	AAWM_ATOM_NET_WM_STATE_SHADED = (AAWM_LAST_X11_PREDEFINED_ATOM + 46),
	AAWM_ATOM_NET_WM_STATE_SKIP_TASKBAR = (AAWM_LAST_X11_PREDEFINED_ATOM + 47),
	AAWM_ATOM_NET_WM_STATE_SKIP_PAGER = (AAWM_LAST_X11_PREDEFINED_ATOM + 48),
	AAWM_ATOM_NET_WM_STATE_HIDDEN = (AAWM_LAST_X11_PREDEFINED_ATOM + 49),
	AAWM_ATOM_NET_WM_STATE_FULLSCREEN = (AAWM_LAST_X11_PREDEFINED_ATOM + 50),
	AAWM_ATOM_NET_WM_STATE_ABOVE = (AAWM_LAST_X11_PREDEFINED_ATOM + 51),
	AAWM_ATOM_NET_WM_STATE_BELOW = (AAWM_LAST_X11_PREDEFINED_ATOM + 52),
	AAWM_ATOM_NET_WM_STATE_DEMANDS_ATTENTION = (AAWM_LAST_X11_PREDEFINED_ATOM + 53),

	AAWM_ATOM_NET_WM_ALLOWED_ACTIONS = (AAWM_LAST_X11_PREDEFINED_ATOM + 54),
	AAWM_ATOM_NET_WM_ACTION_MOVE = (AAWM_LAST_X11_PREDEFINED_ATOM + 55),
	AAWM_ATOM_NET_WM_ACTION_RESIZE = (AAWM_LAST_X11_PREDEFINED_ATOM + 56),
	AAWM_ATOM_NET_WM_ACTION_MINIMIZE = (AAWM_LAST_X11_PREDEFINED_ATOM + 57),
	AAWM_ATOM_NET_WM_ACTION_SHADE = (AAWM_LAST_X11_PREDEFINED_ATOM + 58),
	AAWM_ATOM_NET_WM_ACTION_STICK = (AAWM_LAST_X11_PREDEFINED_ATOM + 59),
	AAWM_ATOM_NET_WM_ACTION_MAXIMIZE_HORZ = (AAWM_LAST_X11_PREDEFINED_ATOM + 60),
	AAWM_ATOM_NET_WM_ACTION_MAXIMIZE_VERT = (AAWM_LAST_X11_PREDEFINED_ATOM + 61),
	AAWM_ATOM_NET_WM_ACTION_FULLSCREEN = (AAWM_LAST_X11_PREDEFINED_ATOM + 62),
	AAWM_ATOM_NET_WM_ACTION_CHANGE_DESKTOP = (AAWM_LAST_X11_PREDEFINED_ATOM + 63),
	AAWM_ATOM_NET_WM_ACTION_CLOSE = (AAWM_LAST_X11_PREDEFINED_ATOM + 64),

	AAWM_ATOM_NET_WM_STRUT = (AAWM_LAST_X11_PREDEFINED_ATOM + 65),
	AAWM_ATOM_NET_WM_STRUT_PARTIAL = (AAWM_LAST_X11_PREDEFINED_ATOM + 66),
	AAWM_ATOM_NET_WM_ICON_GEOMETRY = (AAWM_LAST_X11_PREDEFINED_ATOM + 67),
	AAWM_ATOM_NET_WM_ICON = (AAWM_LAST_X11_PREDEFINED_ATOM + 68),
	AAWM_ATOM_NET_WM_PID = (AAWM_LAST_X11_PREDEFINED_ATOM + 69),
	AAWM_ATOM_NET_WM_HANDLED_ICONS = (AAWM_LAST_X11_PREDEFINED_ATOM + 70),
	AAWM_ATOM_NET_WM_USER_TIME = (AAWM_LAST_X11_PREDEFINED_ATOM + 71),
	AAWM_ATOM_NET_FRAME_EXTENTS = (AAWM_LAST_X11_PREDEFINED_ATOM + 72),

	AAWM_ATOM_NET_WM_PING = (AAWM_LAST_X11_PREDEFINED_ATOM + 73),
	AAWM_ATOM_NET_WM_SYNC_REQUEST = (AAWM_LAST_X11_PREDEFINED_ATOM + 74),
	AAWM_ATOM_NET_WM_SYNC_REQUEST_COUNTER = (AAWM_LAST_X11_PREDEFINED_ATOM + 75),

	AAWM_ATOM_UNKNOWN = (AAWM_LAST_X11_PREDEFINED_ATOM + 76) // for get_symbol_from_atom
} aawm_atom_enum_t;

// AAWM_ATOM_MANAGER
// AAWM_ATOM_WM_LOCALE_NAME

// AAWM_ATOM_MOTIF_WM_HINTS

// AAWM_ATOM_NET_DESKTOP_LAYOUT_Sn
// AAWM_ATOM_WM_Sn
// AAWM_ATOM_NET_WM_STATE_STAYS_ON_TOP

// AAWM_ATOM_NET_WM_USER_TIME_WINDOW
// AAWM_ATOM_NET_WM_OPAQUE_REGION

// Check what XdndAware is.

// Defined in "aawm_ctx.h"
struct aawm_ctx;

const char * get_atom_name( struct aawm_ctx * a_ctx, xcb_atom_t a_atom );
const char ** alloc_atom_names_list( struct aawm_ctx * a_ctx, size_t a_len, xcb_atom_t *a_list );
xcb_atom_t get_atom_from_symbol( struct aawm_ctx * a_ctx, aawm_atom_enum_t a_symbol );
aawm_atom_enum_t get_symbol_from_atom( struct aawm_ctx * a_ctx, xcb_atom_t a_atom );

#endif
